package com.soap;

import java.util.Scanner;

import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;


public class ClientSoap {
	 public static void main(String[] args) {

	        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();        

	        // Use the URL defined in the soap address portion of the WSDL
	        factory.setAddress("http://localhost:8080/ServiceSoap/services/ServiceSoapPort"); 
	       
	        // Utilize the class which was auto-generated by Apache CXF wsdl2java
	        factory.setServiceClass(ServiceSoapInterface.class);        

	        Object client = factory.create();

	        try {        
	    
	            // Call the Web Service to perform an operation
	        	Scanner scan = new Scanner(System.in);
	      	  
	      	  int option = 0;
	      	  while(option!=5) {
	      		  String user = "";
	      		  System.out.println("Select option: \n1.Reserve\n2.Cancel reserve\n3.Show reserves\n4.New user\n5.Quit\n");
	      		  option = scan.nextInt();
	      		  switch(option){
	      		  //Reserve
	      		  case 1:
	      			  System.out.println("User id:\n");
	      			  user = scan.next();
	      			  System.out.println("Beach:\n");
	      			  user = user + "-" + scan.next();
	      			  System.out.println("Hour:\n");
	      			  user = user + "-" + scan.next();
	      			  System.out.println("People:\n");
	      			  user = user + "-" + scan.next();
	      			  System.out.println(user);
	      			  //Conectamos a post
	      			((ServiceSoapInterface)client).addReserve(user);
	      			  break;
	      			  
	      			//Cancelar  
	      		  case 2:
	      			  System.out.println("User id:\n");
	      			  user = scan.next();
	      			  System.out.println("Beach:\n");
	      			  user = user + "-" + scan.next();
	      			  System.out.println("Hour:\n");
	      			  user = user + "-" + scan.next();
	      			((ServiceSoapInterface)client).cancelReserve(user);
	      			  break;
	      			  
	      			  //Enseñar
	      		  case 3:
	      			  System.out.println("Beach:\n");
	      			  user = scan.next();
	      			((ServiceSoapInterface)client).showList(user);
	      			  break;
	      			  
	      			  //Añadir usuario
	      		  case 4:
	      			  System.out.println("User:\n");
	      			  user = scan.next();
	      			((ServiceSoapInterface)client).addUser(user);
	      			  break;
	      			  
	      			  //Exit
	      		  case 5:
	      			  System.out.println("Adiós!\n");
	      			  break;
	      			  
	      		  default:
	      			  System.out.println("Entrada incorrecta.\n");
	      			  break;
	      			  
	      		  }
	      		  
	      	  }
	      	  
	      	scan.close();
	        
	          } catch (SecurityException e) {

	            e.printStackTrace();

	          } catch (IllegalArgumentException e) {

	            e.printStackTrace();

	          }
	        
	    }
	 
}
