
package com.student.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.2
 * Wed Jan 03 16:26:48 CET 2024
 * Generated source version: 3.6.2
 */

@XmlRootElement(name = "autentificar", namespace = "http://student.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "autentificar", namespace = "http://student.com/")

public class Autentificar {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

